// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_coins_grabber = "CgkIn62w990dEAIQCA"; // <GPGSID>
        public const string achievement_ludo_bomber = "CgkIn62w990dEAIQEQ"; // <GPGSID>
        public const string achievement_facebook_champ = "CgkIn62w990dEAIQAg"; // <GPGSID>
        public const string achievement_first_conquest = "CgkIn62w990dEAIQBg"; // <GPGSID>
        public const string achievement_smasher = "CgkIn62w990dEAIQDQ"; // <GPGSID>
        public const string achievement_ludo_starter = "CgkIn62w990dEAIQCw"; // <GPGSID>
        public const string achievement_private_ruler = "CgkIn62w990dEAIQBw"; // <GPGSID>
        public const string achievement_coins_prince = "CgkIn62w990dEAIQEA"; // <GPGSID>
        public const string achievement_ludo_prince = "CgkIn62w990dEAIQDg"; // <GPGSID>
        public const string achievement_coin_emperor = "CgkIn62w990dEAIQFA"; // <GPGSID>
        public const string achievement_snap_up_king = "CgkIn62w990dEAIQDA"; // <GPGSID>
        public const string achievement_king_of_four = "CgkIn62w990dEAIQCQ"; // <GPGSID>
        public const string achievement_fortuner_king = "CgkIn62w990dEAIQEg"; // <GPGSID>
        public const string achievement_head_of_ludo = "CgkIn62w990dEAIQFQ"; // <GPGSID>
        public const string achievement_first_blood = "CgkIn62w990dEAIQBA"; // <GPGSID>
        public const string achievement_dice_possessor = "CgkIn62w990dEAIQAw"; // <GPGSID>
        public const string achievement_link_with_facebook = "CgkIn62w990dEAIQBQ"; // <GPGSID>
        public const string achievement_pawn_destroyer = "CgkIn62w990dEAIQCg"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkIn62w990dEAIQAQ"; // <GPGSID>
        public const string achievement_destroyer_king = "CgkIn62w990dEAIQDw"; // <GPGSID>
        public const string achievement_ludo_emperor = "CgkIn62w990dEAIQEw"; // <GPGSID>

}

