// Generated by Tekrevol
// https://www.tekrevol.com

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace LGSData.Intermediate
{

    public class SocialItem
    {

        [JsonProperty("ItemTime")]
        public string ItemTime { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("ItemType")]
        public string ItemType { get; set; }

        [JsonProperty("Value")]
        public int Value { get; set; }
    }

    public class Data_RAW
    {

        [JsonProperty("SocialItem")]
        public List<SocialItem> SocialItem { get; set; }
    }

}
